### PR TITLE
restructured L00

### PR DESCRIPTION
**Pull request by lwasser**
In this PR - i have restructured L00 to include half of the content from L01. I think focus on data structre upon import to R. And a quick plot of the data. When they plot, it doesn't look pretty given the date is in a character format. So they then have to convert to date field and replot - it magically becomes prettier and faster then. Woo hoo.

There's still lots to do but please have a look at the changes and see what you think. We can then refine content if this seems OK to you.

All of the original content is at the BOTTOM of the page.

### CODE REVIEW

**Comment by lwasser** [comment]
I think it would be good to review this PR and accept it at some point soonish potentially if anyone else will be working on these lessons. Essentially im proposing we focus ONLY on converting to date time (POSIX) in L02. However there is too much detail about 0 based indexing, etc that i think should be additional information rather than in the middle of the lesson. it would be a nice break out box but not necessarily taught in the lesson. The key skills here
1. how to convert to posix
2. how to convert from one time format to another 

The text is all rough and i figure we can all work together to refine the content once we are happy with the shell. I have also renamed the file to be more specific. This will be a nice skillset that lots of people will want to know how to do so the lesson will stand alone nicely will still being a useful part of a set.

**Comment by lwasser** [comment]
Adding l02b - this could become l03. I have several questions at this point. It would be good megan for you to go through l00, 02 and 02b and see what you think. also my is.na result is different from what you guys have. I am getting NA values in date time that may have to do with daylight savings switches. I am not sure if this is a version issue or a code issue or both.

**Comment by mjones01** [comment]
I think the restructuring plans sound good.  I'll go over the "new" lessons on Monday morning.

**Comment by lwasser** [comment]
SOunds good. they are rough.

The NA value thing surrounding daylight savings time is really weird. When you go through it, see if you have the same issues.

**Comment by lwasser** [comment]
Thank you for all of the hard work this week, @mjones01 . have a wonderful weekend! 
leah

**Pull request merged**
