### PR TITLE
Add tags for mainTag & _include Files for Download data

### PR DESCRIPTION
**Pull request by mjones01**

### CODE REVIEW

**Comment by lwasser** [comment]
Hey Megan - i thought we agreed you were working on vector and i was working on time series. I'm working on the tags now .

**Comment by lwasser** [comment]
i've gone through all lessons and edited tags. please leave the yml files and tag yaml front matter alone for the time being so i don't have to work on it twice.

**Comment by mjones01** [comment]
I added the new include files to all the lesson series.  Sorry that I also included the tag yml.  It was one that I'd updated a while ago but since we started only pushing Rmd files I'd forgotten to upload it.  When the PR comes in I'll change any tag merge issues over to your updates.

**Comment by lwasser** [comment]
perfect. thanks. includes are fine. but i just went through and fixed all of the tags so id rather not do that again.I'm committing locally only now.

**Pull request merged**
